title: Opportunity Connect
description: "A site to connect volunteers to opportunities"
<link rel="stylesheet" href="{{ '/assets/main.css' | relative_url }}">
owner_name: Tirth Thakkar
github_username: Tirth-Thakkar
github_repo: "volunteer-frontend"
baseurl: "/volunteer-frontend"
remote_theme: jekyll/minima
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
